version: '3.8'

services:
  springboot:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: springboot
    environment:
      - POSTGRES_USER=graha_citra-api
      - POSTGRES_PASSWORD=XW204Wavz,S98(M
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/graha_citra_db
      - SPRING_DATASOURCE_USERNAME=graha_citra-api
      - SPRING_DATASOURCE_PASSWORD=XW204Wavz,S98(M
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "5123:5123"
    networks:
      db:

networks:
    db:
        driver: host