version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: graha_citra_db
      POSTGRES_USER: graha_citra-api
      POSTGRES_PASSWORD: XW204Wavz,S98(M
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile  # Adjust this path if necessary
    ports:
      - "5123:5123"
    environment:
      - POSTGRES_USER=graha_citra-api
      - POSTGRES_PASSWORD=XW204Wavz,S98(M
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/graha_citra_db
      - SPRING_DATASOURCE_USERNAME=graha_citra-api
      - SPRING_DATASOURCE_PASSWORD=XW204Wavz,S98(M
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FILE_UPLOAD_DIR_PRODUCT_PHOTO=/upload/product
      - FILE_UPLOAD_DIR_WORK_EXP=/upload/work_exp
    volumes:
      - /root/graha-citra-property-back-end/product:/upload/product
      - /root/graha-citra-property-back-end/work_exp:/upload/work_exp
    depends_on:
      - db
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  postgres_data:
