version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: springboot-api
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/graha_citra_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "5123:5123"

  db:
    image: postgres
    container_name: db
    environment:
  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=graha_citra_db
    ports:
      - "5432:5432"