version: '3.8'

services:
  springboot-api:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: springboot-api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/graha_citra_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "5123:5123"
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_network