version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=graha_citra-api
      - POSTGRES_PASSWORD=XW204Wavz,S98(M
      - POSTGRES_DB=graha_citra_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
networks:
  springboot-network:
    driver: bridge

volumes:
  postgres_data: