version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=graha_citra_db
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge