version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=graha_citra-api
      - POSTGRES_PASSWORD=XW204Wavz,S98(M
      - POSTGRES_DB=graha_citra_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - db

networks:
  db:
    driver: host